name: Java Checkstyle

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
