name: Java Checkstyle

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Checkstyle XML report
        run: mvn checkstyle:checkstyle

      - name: Run Checkstyle HTML report
        run: mvn checkstyle:checkstyle-aggregate

      - name: Find Checkstyle reports
        id: find-reports
        run: |
          echo "::set-output name=reports-directory::$(find . -type d \( -name 'checkstyle' -o -name 'checkstyle-aggregate' \))"

      - name: Archive Checkstyle reports
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-reports
          path: ${{ steps.find-reports.outputs.reports-directory }}
